# -*- mode: ruby -*-
# vi: set ft=ruby :

PUBLIC_ADDRESS="10.1.2.4"

Vagrant.configure(2) do |config|

  config.vm.box = "dustybuildRHELAH72"

  # disable default sync for now
  config.vm.synced_folder "./", "/vagrant", disabled: true

  # No need to register
  config.registration.skip = true
  
  config.vm.provider "libvirt" do |v, override|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"

  # Add registry.access.redhat.com to /etc/hosts
  # and configure docker to recognize it as a connection
  config.vm.provision "shell", inline: <<-SHELL
    grep registry.access.redhat.com /etc/hosts || \
        echo '127.0.0.1 registry.access.redhat.com' >> /etc/hosts
    sed -i -e "s/# INSECURE_REGISTRY='--insecure-registry'/INSECURE_REGISTRY='--insecure-registry registry.access.redhat.com'/g" /etc/sysconfig/docker
    systemctl restart docker
  SHELL

  # Make the root LV a bit bigger
  config.vm.provision "shell",
    inline: "lvresize --size=+5g --resizefs atomicos/root"

  # Add the yum repos to the box
  config.vm.provision "file",
    source: "./yumrepos/",
    destination: "/home/vagrant/yumrepos/"
 
  # Add the saved docker images to the box
  config.vm.provision "file",
    source: "./files/",
    destination: "/home/vagrant/files/"

  # import images - start registry - push images to registry
  config.vm.provision "shell", inline: <<-SHELL
  #!/bin/bash
  set -eux
  docker load -i /home/vagrant/files/registry-latest.tar
  docker tag c453594215e4 rhel:7.2
  docker tag c453594215e4 rhel:latest
  mkdir /var/lib/docker-registry
  cd /var/lib/docker-registry
  tar -xf /home/vagrant/files/var-lib-docker-registry.tar
  chcon -R system_u:object_r:svirt_sandbox_file_t:s0 /var/lib/docker-registry
  docker run --restart="always" --name registry -v /var/lib/docker-registry:/var/lib/docker-registry -p 80:5000 -d registry
  SHELL

  # start a server to serve up the yum repos.
  # also need to disable selinux
  config.vm.provision "shell", inline: <<-SHELL
    sed -i s/SELINUX=enforcing/SELINUX=permissive/ /etc/selinux/config
    setenforce 0
    docker run --restart="always" --name yumrepos -d -v /home/vagrant/yumrepos/:/var/lib/yumrepos --workdir /var/lib/yumrepos -p 8000:8000 rhel:7.2 python -m SimpleHTTPServer
  SHELL

  # Add the vagrant insecure key back to the box since we are going to
  # repackage this back up.
  config.vm.provision "shell", inline: <<-'SHELL'
    cat >> ~vagrant/.ssh/authorized_keys << EOKEYS
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOKEYS
  SHELL

# # import images - start registry - push images to registry
# config.vm.provision "shell", inline: <<-SHELL
# #!/bin/bash
# set -eux
# for image in /home/vagrant/images/*.tar; do
#   docker load -i $image
# done
# docker run --restart="always" --name registry -p 80:5000 -d registry
# sleep 15 # wait for it to come up
# IMAGES=(
#   prom/haproxy-exporter:latest
#   rhel:7.2
#   openshift3/ose-pod:v3.1.1.6
#   openshift3/ose-sti-builder:v3.1.1.6
#   openshift3/ose-deployer:v3.1.1.6
#   openshift3/ose:v3.1.1.6
#   openshift3/ose-haproxy-router:v3.1.1.6
#   openshift3/ose-docker-registry:v3.1.1.6
# )
# for image in ${IMAGES[@]}; do
#   echo "Pushing $image to registry"
#   docker push $image
# done
# SHELL

# # Delete all of the images on disk and fstrim
# config.vm.provision "shell",
#   inline: "rm -f /home/vagrant/images/* && fstrim -v /"
#
  # Delete the registry image
  config.vm.provision "shell",
    inline: "rm -f /home/vagrant/files/*"
end
