# -*- mode: ruby -*-
# vi: set ft=ruby :

PUBLIC_ADDRESS="10.1.2.4"

Vagrant.configure(2) do |config|

  config.vm.box = "vagrantRepoHost"
  config.vm.hostname = "vagrantRepoHost"

  # disable default sync for now
  config.vm.synced_folder "./", "/vagrant", disabled: true

  # No need to register
  if Vagrant.has_plugin?("vagrant-registration")
    config.registration.skip = true
  end
  
  config.vm.provider "libvirt" do |v, override|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"

  # Make eth1 be controlled by NM so that we get our ip on bringup
  config.vm.provision "shell", inline: <<-SHELL
    sed -i -e "s/NM_CONTROLLED=no/NM_CONTROLLED=yes/" /etc/sysconfig/network-scripts/ifcfg-eth1
    sed -i -e "s/^HWADDR.*//" /etc/sysconfig/network-scripts/ifcfg-eth1
  SHELL
end
